name: Rust

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test-Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install SDL2
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose